// Tipos de GAME OVER según quién te pilla + frases satíricas
export const ROLE_TYPE = {
  friend: 'friends', partner: 'partner', family: 'family', inlaw: 'family',
  groom: 'couple', bride: 'couple',
  waiter: 'staff', bouncer: 'staff', bartender: 'staff', stall: 'staff',
  security: 'security', police: 'police',
};

export const TYPE_TITLE = {
  friends: 'TUS AMIGOS TE HAN PILLADO',
  staff: 'TE HAN ECHADO DEL LOCAL',
  security: 'SEGURIDAD TE HA PILLADO',
  police: 'LA MUNICIPAL TE HA PILLADO',
  partner: 'TU NOVIA TE HA PILLADO',
  family: 'LA FAMILIA TE HA PILLADO',
  couple: 'LOS NOVIOS TE HAN PILLADO',
};

export const PHRASES = {
  friends: [
    'ESTO VA DIRECTO AL GRUPO DE WHATSAPP.',
    'YA ERES STICKER OFICIAL DEL GRUPO.',
    'TE HAN GRABADO EN 4K. Y EN CÁMARA LENTA.',
    'NUEVO APODO DESBLOQUEADO: EL ASPERSOR.',
    'EL VÍDEO YA TIENE MÁS VISITAS QUE TU BODA.',
    'LO PONDRÁN EN TODOS LOS CUMPLEAÑOS. PARA SIEMPRE.',
  ],
  staff: [
    'VETADO DE POR VIDA. TU FOTO YA ESTÁ EN LA PUERTA.',
    'FUERA. Y LA FREGONA TE LA COBRAMOS APARTE.',
    'TE HAN PUESTO EN LA LISTA... NEGRA.',
    'EL CAMARERO HA DIMITIDO. POR TU CULPA.',
    'TU CARA YA ESTÁ EN EL CARTEL DE "RESERVADO EL DERECHO DE ADMISIÓN".',
  ],
  security: [
    'PULSERA CORTADA. FESTIVAL TERMINADO.',
    'TE HAN SACADO EN VOLANDAS. COMO A UNA ESTRELLA DEL ROCK, PERO SIN FAMA.',
    'SEGURIDAD TE HA HECHO FOTO. PARA EL MURAL DE LA VERGÜENZA.',
    'EL AÑO QUE VIENE LO VES POR STREAMING.',
  ],
  police: [
    'MULTA POR POTAR EN VÍA PÚBLICA: 300 €.',
    'EL MUNICIPAL LO HA APUNTADO EN SU LIBRETA. Y SE LO VA A CONTAR A TU MADRE.',
    'MAÑANA SALES EN EL BANDO DEL AYUNTAMIENTO.',
    'TE TOCA LIMPIAR LA PLAZA. CON CEPILLO DE DIENTES.',
  ],
  partner: [
    'TU NOVIA HA CAMBIADO SU ESTADO A "ES COMPLICADO".',
    'ESTA NOCHE DUERMES EN EL SOFÁ. Y MAÑANA TAMBIÉN.',
    'HA DICHO "NO PASA NADA". PASA TODO.',
    'SE LO VA A CONTAR A SU MADRE. PALABRA POR PALABRA.',
    'YA ESTÁ MIRANDO PISOS DE UNA HABITACIÓN.',
  ],
  family: [
    'TU SUEGRA YA HA ELEGIDO A OTRO YERNO.',
    'TU SUEGRO HA VUELTO A PREGUNTAR A QUÉ TE DEDICAS.',
    'EN LA PRÓXIMA COMIDA FAMILIAR NO HAY PLATO PARA TI.',
    'TU CUÑADO LO CONTARÁ EN CADA NAVIDAD HASTA 2080.',
    'LA ABUELA HA REZADO UN ROSARIO POR TU HÍGADO.',
  ],
  couple: [
    'TU POTA SALDRÁ EN EL VÍDEO DE LA BODA. EN BUCLE.',
    'TE HAN QUITADO DEL ÁLBUM. Y DE SUS VIDAS.',
    'LA NOVIA HA LLORADO. Y NO DE EMOCIÓN.',
    'EL FOTÓGRAFO YA TIENE LA FOTO DEL AÑO.',
  ],
};

export const BREATH_PREFIX = [
  'TE HAN OLIDO EL ALIENTO. ',
  'ESE ALIENTO TE HA DELATADO. ',
];
