// NIVEL 5 — BARBACOA EN CASA DE LA FAMILIA DE LA NOVIA (el más difícil)
import { look, HAIR, SKIN } from './level.js';

export default {
  id: 'barbacoa',
  name: 'BARBACOA',
  intro: 'DOMINGO, 14:00. COMIDA EN CASA DE TUS SUEGROS. AYER FUE LA DESPEDIDA DE TU CUÑADO. TU SUEGRO SACA LAS PANCETAS.',
  music: 'barbacoa',
  palette: {
    ink: '#18140c', wallTop: '#a8584a', wallFace: '#f0e0c0', wallLine: '#d8c49c',
    wood: '#b07840', woodDark: '#7a4c24', woodLight: '#d8a068', metal: '#a8a8b8', metalDark: '#383840',
    accent: '#d84848', accent2: '#4898d8', leaf: '#48a040', leafDark: '#2a6a2a', leafLight: '#88d068',
    cloth: '#f8f8f8', clothShade: '#d0d0e0', water: '#48a8e8', waterLight: '#c0ecff', stone: '#e0dccc',
    counter: '#e8e0d0', shelf: '#b8b0a0', sofa: '#6a8a48', sofaDark: '#4a6a30', car: '#c83838', cooler: '#3890d8',
    void: '#141810',
  },
  floors: {
    '.': ['wood', '#d8b080', '#c09868'],
    ':': ['tiles', '#e8f0f8', '#c8d0e0'],
    "'": ['grass', '#70b850', '#58a040', '#f8f0a0'],
    'v': ['veg', '#8a6038', '#6a4420', '#58b040'],
    '-': ['stone', '#a0a098', '#88887e'],
    'd': ['mat', '#d8b080', '#8a4a38'],
  },
  floorUnder: { 't': ':', 'K': '-' },
  map: [
    '##################################',
    '#I..CCC.#kkkkkIk#t:t#XX-------IX-#',
    '#.......#.......#:::#---KKK-----X#',
    '#...T...#...T...#:::#---KKK-----I#',
    '#.......#.......#:::#---KKK------#',
    '####d#######d#####d##---KKK------#',
    '#...................d------------#',
    '#...................#--------XX--#',
    '####d#####..........#---------X--#',
    '#b.....I#...TTTT....#------------#',
    '#b......#...TTTT....###-----######',
    "#########d####d######''''''''''''#",
    "#''''''''''''''''''''''''''''''''#",
    "#''TTTTTTTTTT''''G''''''''''''''B#",
    "#''''''''''''''''x'''''''''''''''#",
    "#B''''''''''''''''''~~~~~~~~~''''#",
    "#''''''B''''''''''''~~~~~~~~~''b'#",
    "#''''''''''MMM''''''~~~~~~~~~''b'#",
    "#''''''''''MMM''''''~~~~~~~~~''''#",
    "#'''''''''''''''''''~~~~~~~~~''''#",
    "#HHHHHH'HH''''''''''''''''''''B''#",
    "#vvvvvvvvv''''''B''''''''''''''''#",
    "#vvvvvvvvv''''''''''''''''''HHHHH#",
    "#vvvvvvvvv''''''''B'''''''''H''''#",
    "#vvvvvvvvv''''''''''''''''''H'XX'#",
    "#XXvvvvvvv''''''''''''''''''''XX'#",
    "#''''''''''''''''''''''''''''''''#",
    '##################################',
  ],
  player: [26, 12],
  npcs: [
    {
      kind: 'A', role: 'family', name: 'PRIMO', label: 'PRIMO',
      look: look({ style: 'cap', cap: '#3a3a44', hair: HAIR.black, skin: SKIN[2] }),
      route: [[31, 13, 3, 'left'], [32, 26, 3, 'up'], [16, 26, 2, 'up'], [1, 21, 3, 'right'], [10, 17, 1]],
    },
    {
      kind: 'A', role: 'family', name: 'TÍA', label: 'TÍA',
      look: look({ style: 'bun', hair: HAIR.red, skin: SKIN[1], body: 'dress', glasses: true }),
      route: [[1, 12, 3, 'right'], [7, 20, 2], [4, 24, 3, 'down'], [20, 24, 2], [28, 20, 2, 'down'], [16, 12, 2]],
    },
    {
      kind: 'A', role: 'family', name: 'TÍO', label: 'TÍO',
      look: look({ style: 'short', hair: HAIR.grey, skin: SKIN[2], body: 'belly', mustache: true, glasses: true }),
      route: [[28, 5, 5, 'up'], [22, 6, 0], [4, 2, 4, 'up'], [7, 12, 4, 'down'], [28, 11, 0]],
    },
    {
      kind: 'A', role: 'family', name: 'PRIMA', label: 'PRIMA',
      look: look({ style: 'bun', hair: HAIR.red, skin: SKIN[0], body: 'dress' }),
      route: [[31, 15, 4, 'left'], [11, 22, 3, 'left'], [29, 24, 3, 'up'], [20, 21, 2]],
    },
    { kind: 'B', role: 'kid', route: [[3, 17, 0], [17, 15, 1], [12, 25, 0]], look: look({ kid: true, shirt: '#e84848', hair: HAIR.red }) },
    { kind: 'B', role: 'neighbor', behavior: 'static', at: [24, 20], dir: 'up', look: look({ style: 'cap', cap: '#4898d8', shirt: '#f8f8f8', hair: HAIR.brown }) },
    { kind: 'B', role: 'neighbor', behavior: 'static', at: [13, 8], dir: 'down', look: look({ style: 'long', body: 'dress', shirt: '#a858a8', hair: HAIR.black }) },
    { kind: 'B', role: 'neighbor', behavior: 'static', at: [2, 13], dir: 'right', look: look({ shirt: '#d8a838', hair: HAIR.grey, body: 'belly' }) },
    {
      kind: 'A', role: 'partner', name: 'ANDREINA',
      look: look({ style: 'long', hair: HAIR.dark, skin: SKIN[1], body: 'dress' }),
      route: [[5, 14, 5, 'up'], [12, 2, 4, 'up'], [10, 6, 0], [18, 3, 4, 'up'], [10, 12, 0], [8, 14, 3, 'up']],
    },
    {
      kind: 'A', role: 'inlaw', name: 'SUEGRO', label: 'SUEGRO',
      look: look({ style: 'bald', hair: SKIN[1], skin: SKIN[1], body: 'belly', mustache: true, shirt: '#f060a8' }),
      route: [[16, 14, 6, 'up'], [26, 7, 5, 'up'], [19, 14, 2, 'down'], [16, 12, 3, 'down']],
    },
    {
      kind: 'A', role: 'inlaw', name: 'SUEGRA', label: 'SUEGRA',
      look: look({ style: 'bun', hair: HAIR.grey, skin: SKIN[0], body: 'dress', glasses: true }),
      route: [[10, 2, 6, 'up'], [3, 2, 3, 'left'], [9, 12, 2, 'down'], [4, 12, 5, 'down'], [12, 7, 0]],
    },
    {
      kind: 'A', role: 'family', name: 'CUÑADO', label: 'CUÑADO',
      look: look({ style: 'cap', cap: '#f8f8f8', hair: HAIR.black, skin: SKIN[2], beard: true }),
      route: [[19, 17, 5, 'right'], [14, 19, 3, 'up'], [10, 23, 3, 'left'], [29, 8, 4, 'up'], [24, 12, 0]],
    },
    {
      kind: 'A', role: 'family', name: 'CUÑADA', label: 'CUÑADA',
      look: look({ style: 'long', hair: HAIR.blond, skin: SKIN[5], body: 'dress' }),
      route: [[30, 18, 6, 'left'], [25, 21, 2], [10, 14, 4, 'up'], [4, 7, 3, 'down'], [15, 12, 0]],
    },
    {
      kind: 'A', role: 'family', name: 'ABUELA', label: 'ABUELA',
      look: look({ style: 'bun', hair: HAIR.white, skin: SKIN[0], body: 'dress', glasses: true, shirt: '#f060a8' }),
      route: [[5, 21, 6, 'down'], [12, 21, 0], [3, 14, 6, 'up'], [7, 20, 0]],
    },
    // ---- NPC-B: vecinos, niños y perro ----
    { kind: 'B', role: 'neighbor', behavior: 'static', at: [18, 12], dir: 'left', look: look({ style: 'short', hair: HAIR.grey, shirt: '#4898d8', body: 'belly', mustache: true }) },
    { kind: 'B', role: 'neighbor', behavior: 'static', at: [23, 3], dir: 'right', look: look({ style: 'long', hair: HAIR.red, shirt: '#58a048', body: 'dress' }) },
    { kind: 'B', role: 'kid', route: [[6, 17, 0], [18, 20, 0], [30, 21, 1], [22, 13, 0]], look: look({ kid: true, shirt: '#f8c838', hair: HAIR.black }) },
    { kind: 'B', role: 'kid', route: [[30, 14, 0], [13, 16, 1], [4, 18, 0], [16, 22, 1]], look: look({ kid: true, style: 'long', body: 'dress', shirt: '#58c8e8', hair: HAIR.blond }) },
    { kind: 'B', role: 'dog', name: 'TOBY', route: [[20, 13, 2], [9, 16, 1], [15, 24, 2], [27, 22, 1], [28, 12, 2]],
      look: { dog: true, outline: '#2a1c14', fur: '#c88848', spot: '#f0e0c8' } },
  ],
  items: [
    ['pitillo', 32, 4], ['pitillo', 19, 4], ['pitillo', 6, 10], ['pitillo', 9, 25], ['pitillo', 32, 25],
    ['botella', 1, 26],
  ],
};
