// NIVEL 3 — BODA
import { look, HAIR, SKIN } from './level.js';

export default {
  id: 'boda',
  name: 'BODA',
  intro: 'SE CASA TU AMIGO JORGE. BARRA LIBRE DESDE LAS 18:00. SON LAS 23:00. TU NOVIA Y TU SUEGRA ESTÁN AQUÍ.',
  music: 'boda',
  palette: {
    ink: '#1c1418', wallTop: '#c8b8a0', wallFace: '#e8dcc8', wallLine: '#c0b098',
    wood: '#a06838', woodDark: '#6a4020', woodLight: '#d09860', metal: '#b0b0c0', metalDark: '#404050',
    accent: '#d84868', accent2: '#58a8d8', leaf: '#48a048', leafDark: '#2a6a30', leafLight: '#88d070',
    cloth: '#f8f8f8', clothShade: '#d0d0e0', water: '#4890e0', waterLight: '#b8e0f8', stone: '#c8c0b0',
    counter: '#e0d8c8', shelf: '#c8c0b0', glass: '#e8f8f8', void: '#141018',
  },
  floors: {
    '.': ['wood', '#c08858', '#a87040'],
    ',': ['checker', '#f0e8e0', '#c8b8c8'],
    ':': ['tiles', '#e8e8f0', '#c8c8d8'],
    ';': ['stone', '#d8c8a8', '#b8a888'],
    "'": ['grass', '#68b048', '#509038', '#f8f0f0'],
    '-': ['stone', '#a8a098', '#888078'],
  },
  floorUnder: { 't': ':', 'k': ':' },
  map: [
    '##################################',
    '#t:t#P.TTTTTTTTTTTT.P..#kkkk::kkI#',
    '#:::#..................#::::::::I#',
    '#:::d..R...R...R...R...d:::::::::#',
    '#####...............=..#kkk:::kkk#',
    '#t:t#...R...R...R...=..#:::::::::#',
    '#:::d...............=..#####d#####',
    '#:::#...R...R...R...=..#....;....#',
    '#####..................#....;....#',
    '#P.......,,,,,,,,,,....#....;....#',
    '#........,,,,,,,,,,..S.#....;....#',
    '#..R.....,,,,,,,,,,....d;;;;;....#',
    '#........,,,,,,,,,,..S.#....;....#',
    '#P..R...............R..#....;....#',
    "###########;;###########....;....#",
    "#''''''''''';;'''''''''''''';''''#",
    "#'ccc'''B''';;'''''''B''''';''B''#",
    "#''''''''''';;'''''''''''''';''''#",
    "#''HHHH''''';;;;;;;;;;;;;;;;;''''#",
    "#''H'''''''';'''''Y''''';''''''''#",
    "#''H''B'''''';'''''''''';''HHHHH'#",
    "#''H''''''''';;;;;;;;;;;;''H-----#",
    "#''HHH''B''''''''''''''''''H-n-n-#",
    "#''''''''''''B'''''''B'''''H-----#",
    "#'c''B''''''''''''''''''''''----P#",
    "#''''''''c'c'c''''''''''B''H-n-n-#",
    "#''''''''''''''''''''''''''H----P#",
    '##################################',
  ],
  player: [12, 15],
  npcs: [
    {
      kind: 'A', role: 'friend', name: 'F6',
      look: look({ style: 'short', hair: HAIR.black, skin: SKIN[2], shirt: '#f060a8', bowtie: '#282838' }),
      route: [[16, 6, 4, 'left'], [19, 5, 3, 'right'], [6, 19, 3], [12, 15, 1], [16, 6, 0]],
    },
    {
      kind: 'A', role: 'friend', name: 'F7',
      look: look({ style: 'long', hair: HAIR.blond, skin: SKIN[5], body: 'dress' }),
      route: [[15, 11, 4], [24, 11, 0], [30, 22, 5, 'down'], [24, 11, 0], [6, 12, 3, 'right']],
    },
    { kind: 'B', role: 'guest', behavior: 'static', at: [10, 7], dir: 'left', look: look({ style: 'bald', hair: SKIN[1], shirt: '#384868', body: 'belly' }) },
    { kind: 'B', role: 'guest', behavior: 'static', at: [16, 3], dir: 'left', look: look({ style: 'bun', body: 'dress', shirt: '#a84868', hair: HAIR.grey }) },
    { kind: 'B', role: 'guest', behavior: 'static', at: [2, 10], dir: 'right', look: look({ shirt: '#5a8a48', hair: HAIR.brown }) },
    { kind: 'B', role: 'guest', behavior: 'static', at: [22, 17], dir: 'left', look: look({ style: 'long', body: 'dress', shirt: '#58a8d8', hair: HAIR.black }) },
    { kind: 'B', role: 'guest', behavior: 'static', at: [9, 24], dir: 'up', look: look({ shirt: '#686868', hair: HAIR.grey, body: 'belly' }) },
    { kind: 'B', role: 'kid', route: [[20, 24, 1], [30, 17, 0], [14, 20, 1]], look: look({ kid: true, style: 'bun', body: 'dress', shirt: '#f070b0', hair: HAIR.brown }) },
    {
      kind: 'A', role: 'bride', name: 'LUCÍA', label: 'NOVIA',
      look: look({ style: 'bun', hair: HAIR.brown, skin: SKIN[0], shirt: '#fcfcfc', body: 'dress', veil: true }),
      route: [[12, 2, 5, 'down'], [14, 10, 4], [16, 17, 3, 'down'], [20, 16, 3, 'left'], [12, 2, 0]],
    },
    {
      kind: 'A', role: 'groom', name: 'JORGE', label: 'NOVIO',
      look: look({ style: 'short', hair: HAIR.black, skin: SKIN[1], shirt: '#282838', pants: '#282838', bowtie: '#f8f8f8', beard: true }),
      route: [[13, 2, 4, 'down'], [19, 6, 3, 'right'], [29, 23, 5, 'left'], [24, 11, 0], [14, 11, 3, 'down']],
    },
    {
      kind: 'A', role: 'partner', name: 'ANDREINA',
      look: look({ style: 'long', hair: HAIR.dark, skin: SKIN[1], body: 'dress', shirt: '#f060a8' }),
      route: [[8, 4, 5, 'up'], [2, 6, 4, 'up'], [12, 12, 4], [6, 17, 3, 'left'], [8, 4, 0]],
    },
    {
      kind: 'A', role: 'inlaw', name: 'CARMEN', label: 'SUEGRA',
      look: look({ style: 'bun', hair: HAIR.grey, skin: SKIN[0], body: 'dress', glasses: true }),
      route: [[12, 6, 6, 'down'], [19, 7, 3, 'right'], [10, 21, 4, 'down'], [12, 13, 0]],
    },
    {
      kind: 'A', role: 'friend', name: 'RAÚL',
      look: look({ style: 'cap', cap: '#282838', hair: HAIR.red, skin: SKIN[0], beard: true }),
      route: [[2, 2, 3, 'up'], [20, 12, 3, 'left'], [30, 23, 6, 'up'], [28, 12, 0], [11, 13, 2, 'left']],
    },
    // ---- Staff ----
    {
      kind: 'B', role: 'waiter', name: 'CAMARERO', worker: true, zone: [[24, 1, 9, 5]],
      look: look({ shirt: '#f4f4f4', pants: '#181818', bowtie: '#181818', hair: HAIR.black, skin: SKIN[2] }),
      route: [[27, 3, 2, 'up'], [23, 3, 0], [10, 4, 1, 'down'], [15, 8, 1], [29, 2, 3, 'up'], [28, 7, 0], [28, 12, 1], [28, 5, 0]],
    },
    { kind: 'B', role: 'waiter', name: 'CAMARERA', worker: true, zone: [[24, 1, 9, 5]], route: [[30, 3, 3, 'right'], [25, 2, 3, 'up']],
      look: look({ style: 'bun', shirt: '#f4f4f4', pants: '#181818', hair: HAIR.black, skin: SKIN[1] }) },
    { kind: 'B', role: 'bartender', name: 'BARMAN', worker: true, zone: [[21, 4, 2, 4]], behavior: 'guard', at: [22, 5], dir: 'left',
      look: look({ shirt: '#282838', pants: '#181818', bowtie: '#d84868', hair: HAIR.blond, skin: SKIN[0] }) },
    // ---- Invitados ajenos, fotógrafo, DJ ----
    { kind: 'B', role: 'photographer', name: 'FOTÓGRAFO', route: [[16, 16, 4, 'up'], [8, 12, 3], [26, 18, 3], [18, 22, 3, 'up']],
      look: look({ style: 'cap', cap: '#181818', shirt: '#484858', hair: HAIR.brown }) },
    { kind: 'B', role: 'dj', behavior: 'dance', at: [20, 11], dir: 'left', look: look({ shirt: '#181818', hair: HAIR.blue, skin: SKIN[3] }) },
    ...[[10, 9], [13, 10], [16, 9], [11, 12], [15, 12], [17, 11]].map(([x, y], i) => ({
      kind: 'B', role: 'guest', behavior: 'dance', at: [x, y], dir: 'down',
      look: look({ style: ['short', 'long', 'bun'][i % 3], body: i % 3 ? 'dress' : 'normal', shirt: ['#3848a8', '#58a8d8', '#d8a838', '#5a8a48', '#a83838', '#8858a8'][i], hair: [HAIR.black, HAIR.blond, HAIR.brown, HAIR.grey][i % 4], skin: SKIN[(i + 2) % 5] }),
    })),
    ...[[6, 3, 'right'], [9, 5, 'left'], [14, 7, 'left'], [18, 3, 'right'], [4, 11, 'right'], [21, 13, 'left']].map(([x, y, d], i) => ({
      kind: 'B', role: 'guest', behavior: 'static', at: [x, y], dir: d,
      look: look({ style: ['short', 'bun', 'bald', 'long'][i % 4], body: i % 2 ? 'dress' : 'belly', shirt: ['#384868', '#a84868', '#486848', '#686868', '#b89838', '#6848a8'][i], hair: [HAIR.grey, HAIR.brown, SKIN[1], HAIR.black][i % 4], skin: SKIN[i % 4] }),
    })),
    { kind: 'B', role: 'kid', behavior: 'route', route: [[5, 16, 1], [20, 19, 0], [10, 25, 1], [2, 20, 0]],
      look: look({ kid: true, shirt: '#58a8d8', hair: HAIR.blond, pants: '#303850' }) },
  ],
  items: [['pitillo', 30, 24], ['pitillo', 2, 9], ['pitillo', 25, 8], ['chicle', 2, 7], ['sobras', 6, 1], ['botella', 1, 26]],
};
