// NIVEL 2 — FESTIVAL
import { look, HAIR, SKIN } from './level.js';

export default {
  id: 'festival',
  name: 'FESTIVAL',
  intro: 'TERCER DÍA DE FESTIVAL. HAS DESAYUNADO CERVEZA CALIENTE Y UN BOCATA DE FOOD TRUCK DE 14 EUROS. MALA IDEA.',
  music: 'festival',
  palette: {
    ink: '#18140c', wallTop: '#586838', wallFace: '#405028', wallLine: '#304018',
    wood: '#a07040', woodDark: '#6a4828', woodLight: '#c89860', metal: '#9098a8', metalDark: '#2a2a34',
    accent: '#e84830', accent2: '#3890e8', leaf: '#48a038', leafDark: '#2a6a28', leafLight: '#88d060',
    fence: '#c0c8d0', water: '#3888d8', waterLight: '#a8d8f8', truck: '#f0e0b0', screen: '#302850',
    toilet: '#3870c8', toiletTop: '#78a8e8', toiletDark: '#284c90', cooler: '#e84830', void: '#1a2410',
  },
  floors: {
    '.': ['grass', '#68b048', '#509038', '#f8e060'],
    ',': ['dirt', '#9c7c4c', '#84643c'],
    ';': ['dirt', '#c0a070', '#a88858'],
    ':': ['wood', '#8a6038', '#704a28'],
    "'": ['grass', '#58a040', '#40802c', '#f070b0'],
    '_': ['stage', '#4a3a48', '#302430'],
    '-': ['dirt', '#9a9488', '#848074'],
  },
  floorUnder: { 'X': '-', 'x': '.' },
  map: [
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    'F..B....XX..WWWWWWWWWWWWWW..XX....BF',
    'F.......X..S______________S..X.....F',
    'F..........S______________S........F',
    'F...B..............................F',
    'F..................................F',
    'F..........,,,,,,,,,,,,,,,.........F',
    'F.=====....,,,,,,,,,,,,,,,...LLL...F',
    'F.:::::....,,,,,,,,,,,,,,,...LLL...F',
    'F.:::::....,,,,,,,,,,,,,,,.........F',
    'F.=====....,,,,,,,,,,,,,,,...LLL...F',
    'F..........,,,,,,,,,,,,,,,...LLL...F',
    'F....B.............................F',
    'F...............B.........x..x.....F',
    'F..........;;;;;;;;;;;;;;;.........F',
    "F..........;..............''''''''.F",
    "F..QQ.QQ.QQ;.....B........''n''n''.F",
    "F..........;..............''''''''.F",
    "F..........;.......x......'B''''B'.F",
    "F;;;;;;;;;;;;;;;;;;;;;;;;;''''''''.F",
    "F..........;..............''n''n''.F",
    "FFFFFFFF.FFFFFFFFFFFFFFFFF''''''''.F",
    'F--X----.---X----X-------F.........F',
    'F------------------------F..B...B..F',
    'F-XX----X-----XX-----X---F.........F',
    'F-------------------------.........F',
    'F--X-------X--------X----F....B....F',
    'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
  ],
  player: [18, 14],
  npcs: [
    {
      kind: 'A', role: 'friend', name: 'F5',
      look: look({ style: 'long', hair: HAIR.pink, skin: SKIN[0], body: 'dress' }),
      route: [[27, 12, 3, 'right'], [29, 20, 4, 'up'], [18, 19, 2], [22, 11, 3, 'up']],
    },
    {
      kind: 'A', role: 'friend', name: 'F6',
      look: look({ style: 'short', hair: HAIR.brown, skin: SKIN[3], beard: true }),
      route: [[8, 8, 3, 'left'], [10, 18, 3, 'up'], [2, 13, 2], [9, 4, 3, 'right']],
    },
    ...[[14, 6], [20, 10], [25, 8], [15, 10]].map(([x, y], i) => ({
      kind: 'B', role: 'crowd', behavior: 'dance', at: [x, y], dir: 'up',
      look: look({ style: ['cap', 'long', 'short', 'bun'][i], body: i % 2 ? 'dress' : 'normal', cap: '#f8c838', shirt: ['#e84830', '#38c8e8', '#f8f8f8', '#8848e8'][i], hair: [HAIR.black, HAIR.blond, HAIR.red, HAIR.brown][i], skin: SKIN[(i + 1) % 5] }),
    })),
    { kind: 'B', role: 'crowd', behavior: 'static', at: [28, 12], dir: 'right', look: look({ style: 'long', body: 'dress', shirt: '#f8c838', hair: HAIR.red }) },
    { kind: 'B', role: 'crowd', behavior: 'static', at: [27, 17], dir: 'right', look: look({ shirt: '#303030', hair: HAIR.black, body: 'belly' }) },
    { kind: 'B', role: 'dog', name: 'KIRA', route: [[5, 5, 2], [9, 13, 1], [20, 16, 2], [32, 14, 1], [33, 4, 2]], look: { dog: true, outline: '#2a1c14', fur: '#e8e0d0', spot: '#303030' } },
    {
      kind: 'A', role: 'friend', name: 'JAVI',
      look: look({ hair: HAIR.black, skin: SKIN[2], beard: true, style: 'cap', cap: '#e8e8e8' }),
      route: [[14, 8, 4, 'up'], [7, 9, 3, 'left'], [6, 18, 3, 'up'], [11, 17, 0], [18, 11, 3, 'up']],
    },
    {
      kind: 'A', role: 'friend', name: 'NURIA', label: 'AMIGA',
      look: look({ style: 'bun', hair: HAIR.red, skin: SKIN[0], body: 'dress' }),
      route: [[27, 8, 3, 'right'], [27, 12, 2, 'down'], [28, 17, 4, 'left'], [20, 19, 0], [20, 9, 3, 'up']],
    },
    {
      kind: 'A', role: 'friend', name: 'SERGIO',
      look: look({ style: 'short', hair: HAIR.blond, skin: SKIN[1], glasses: true }),
      route: [[17, 5, 4, 'up'], [24, 5, 0], [9, 18, 3, 'up'], [11, 15, 0], [4, 12, 2, 'left'], [15, 5, 2, 'up']],
    },
    {
      kind: 'A', role: 'partner', name: 'ANDREINA',
      look: look({ style: 'long', hair: HAIR.dark, skin: SKIN[1], body: 'dress' }),
      route: [[30, 20, 5, 'left'], [22, 16, 2], [27, 9, 3, 'right'], [11, 12, 3, 'down'], [30, 16, 2, 'left']],
    },
    // ---- Staff ----
    {
      kind: 'B', role: 'security', name: 'SEGURATA', worker: true, zone: [[1, 22, 24, 5]],
      look: look({ style: 'bald', hair: SKIN[3], skin: SKIN[3], shirt: '#f8d020', pants: '#181818', badge: '#181818', body: 'belly' }),
      route: [[3, 23, 2, 'right'], [20, 23, 2, 'left'], [20, 25, 1], [3, 25, 2, 'right']],
    },
    { kind: 'B', role: 'security', name: 'SEGURIDAD', worker: true, zone: [[10, 4, 18, 2]], behavior: 'guard', at: [18, 4], dir: 'down',
      look: look({ style: 'short', hair: HAIR.black, skin: SKIN[4], shirt: '#f8d020', pants: '#181818', badge: '#181818' }) },
    { kind: 'B', role: 'bartender', name: 'CAMARERO', worker: true, zone: [[1, 7, 6, 4]], behavior: 'guard', at: [3, 8], dir: 'right',
      look: look({ style: 'cap', cap: '#e84830', shirt: '#e84830', pants: '#303030', hair: HAIR.brown }) },
    { kind: 'B', role: 'bartender', name: 'CAMARERA', worker: true, zone: [[1, 7, 6, 4]], route: [[5, 9, 3, 'right'], [2, 8, 2, 'right']],
      look: look({ style: 'long', shirt: '#e84830', pants: '#303030', hair: HAIR.blond, body: 'dress' }) },
    // ---- Músicos ----
    { kind: 'B', role: 'band', behavior: 'dance', at: [15, 2], dir: 'down', look: look({ style: 'long', shirt: '#181818', hair: HAIR.black }) },
    { kind: 'B', role: 'band', behavior: 'dance', at: [19, 3], dir: 'down', look: look({ style: 'cap', cap: '#e84830', shirt: '#f8f8f8', hair: HAIR.blond }) },
    { kind: 'B', role: 'band', behavior: 'dance', at: [23, 2], dir: 'down', look: look({ style: 'short', shirt: '#3890e8', hair: HAIR.red, beard: true }) },
    // ---- Público ----
    ...[[12, 6], [15, 7], [18, 6], [21, 7], [24, 6], [13, 9], [17, 9], [20, 8], [23, 10], [12, 11], [16, 11], [19, 11], [22, 9]].map(([x, y], i) => ({
      kind: 'B', role: 'crowd', behavior: 'dance', at: [x, y], dir: 'up',
      look: look({
        style: ['short', 'long', 'cap', 'bun', 'short', 'long'][i % 6], body: i % 3 === 1 ? 'dress' : 'normal',
        shirt: ['#38c8e8', '#f8c838', '#58c048', '#8848e8', '#e86830', '#f8f8f8', '#303030'][i % 7],
        hair: [HAIR.black, HAIR.brown, HAIR.blond, HAIR.red, HAIR.pink, HAIR.blue][i % 6], cap: '#3890e8', skin: SKIN[i % 5],
      }),
    })),
    { kind: 'B', role: 'crowd', behavior: 'static', at: [28, 9], dir: 'right', look: look({ shirt: '#58c048', hair: HAIR.brown, body: 'belly' }) },
    { kind: 'B', role: 'crowd', behavior: 'static', at: [4, 18], dir: 'up', look: look({ style: 'long', shirt: '#f8c838', hair: HAIR.black, body: 'dress' }) },
    { kind: 'B', role: 'crowd', behavior: 'static', at: [7, 17], dir: 'up', look: look({ shirt: '#3890e8', hair: HAIR.red }) },
    { kind: 'B', role: 'crowd', behavior: 'static', at: [30, 15], dir: 'down', look: look({ style: 'bun', shirt: '#f070b0', hair: HAIR.blond, body: 'dress' }) },
    { kind: 'B', role: 'crowd', route: [[33, 5, 3], [33, 25, 3], [27, 25, 2]], look: look({ style: 'cap', cap: '#58c048', shirt: '#303030' }) },
  ],
  items: [['pitillo', 33, 2], ['pitillo', 3, 14], ['pitillo', 30, 25], ['pitillo', 14, 15], ['sobras', 33, 9], ['botella', 12, 23], ['mechero', 1, 15]],
};
